#!/usr/bin/env python3
"""
PECH Group Holdings Ltd — DOCX Branding Post-Processor

Applies PECH brand colors, styled headers, colored dividers, and table formatting
to Word documents generated by pandoc (which strips all HTML styling).

Usage:
    python3 scripts/brand_docx.py                    # Process ALL docx files
    python3 scripts/brand_docx.py path/to/file.docx  # Process a single file

Brand Colors:
    Sky Blue:    #00BFFF  (primary)
    Orange:      #F5A623  (secondary/accent)
    Dark Blue:   #0099CC  (headings)
    Dark Orange: #E08A00  (H3 headings)
    Dark Navy:   #1B2838  (backgrounds)
"""

import os
import sys
import re
from pathlib import Path
from copy import deepcopy

from docx import Document
from docx.shared import Pt, Inches, Cm, RGBColor, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml

PROJECT_ROOT = Path(__file__).parent.parent

# ── Brand Colors ──────────────────────────────────────────────────────────────
SKY_BLUE = RGBColor(0x00, 0xBF, 0xFF)
DARK_BLUE = RGBColor(0x00, 0x99, 0xCC)
ORANGE = RGBColor(0xF5, 0xA6, 0x23)
DARK_ORANGE = RGBColor(0xE0, 0x8A, 0x00)
DARK_NAVY = RGBColor(0x1B, 0x28, 0x38)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT_BLUE_BG = RGBColor(0xE8, 0xF8, 0xFF)  # Even row tint
BODY_TEXT = RGBColor(0x1A, 0x1A, 0x1A)

# Hex strings for XML (no # prefix)
HEX_SKY_BLUE = "00BFFF"
HEX_DARK_BLUE = "0099CC"
HEX_ORANGE = "F5A623"
HEX_DARK_ORANGE = "E08A00"
HEX_DARK_NAVY = "1B2838"
HEX_WHITE = "FFFFFF"
HEX_LIGHT_BLUE = "E8F8FF"
HEX_BORDER_LIGHT = "B0D4E8"


def set_paragraph_border_bottom(paragraph, color_hex, size_eighths=12, space=1):
    """Add a colored bottom border to a paragraph (used for dividers and H1/H2 underlines)."""
    pPr = paragraph._element.get_or_add_pPr()
    pBdr = pPr.find(qn('w:pBdr'))
    if pBdr is None:
        pBdr = parse_xml(f'<w:pBdr {nsdecls("w")}></w:pBdr>')
        pPr.append(pBdr)
    bottom = parse_xml(
        f'<w:bottom {nsdecls("w")} w:val="single" w:sz="{size_eighths}" '
        f'w:space="{space}" w:color="{color_hex}"/>'
    )
    # Remove existing bottom if any
    existing = pBdr.find(qn('w:bottom'))
    if existing is not None:
        pBdr.remove(existing)
    pBdr.append(bottom)


def set_paragraph_border_top(paragraph, color_hex, size_eighths=12, space=1):
    """Add a colored top border to a paragraph."""
    pPr = paragraph._element.get_or_add_pPr()
    pBdr = pPr.find(qn('w:pBdr'))
    if pBdr is None:
        pBdr = parse_xml(f'<w:pBdr {nsdecls("w")}></w:pBdr>')
        pPr.append(pBdr)
    top = parse_xml(
        f'<w:top {nsdecls("w")} w:val="single" w:sz="{size_eighths}" '
        f'w:space="{space}" w:color="{color_hex}"/>'
    )
    existing = pBdr.find(qn('w:top'))
    if existing is not None:
        pBdr.remove(existing)
    pBdr.append(top)


def set_run_color(run, rgb_color):
    """Set the font color of a run."""
    run.font.color.rgb = rgb_color


def set_all_runs_color(paragraph, rgb_color):
    """Set font color for all runs in a paragraph."""
    for run in paragraph.runs:
        run.font.color.rgb = rgb_color


def set_cell_shading(cell, color_hex):
    """Set background shading on a table cell."""
    shading = parse_xml(
        f'<w:shd {nsdecls("w")} w:fill="{color_hex}" w:val="clear"/>'
    )
    cell._tc.get_or_add_tcPr().append(shading)


def set_cell_text_color(cell, rgb_color):
    """Set font color for all text in a cell."""
    for paragraph in cell.paragraphs:
        for run in paragraph.runs:
            run.font.color.rgb = rgb_color


def insert_branded_divider(doc, before_element, style="double"):
    """
    Insert a branded colored divider (horizontal rule) before a given element.
    Uses a two-line approach: orange top line + blue bottom line.
    """
    if style == "double":
        # Create a paragraph with both top and bottom colored borders
        divider = parse_xml(
            f'<w:p {nsdecls("w")}>'
            f'  <w:pPr>'
            f'    <w:pBdr>'
            f'      <w:top w:val="single" w:sz="18" w:space="1" w:color="{HEX_ORANGE}"/>'
            f'      <w:bottom w:val="single" w:sz="6" w:space="1" w:color="{HEX_DARK_BLUE}"/>'
            f'    </w:pBdr>'
            f'    <w:spacing w:before="200" w:after="200"/>'
            f'  </w:pPr>'
            f'</w:p>'
        )
    else:
        # Single orange line
        divider = parse_xml(
            f'<w:p {nsdecls("w")}>'
            f'  <w:pPr>'
            f'    <w:pBdr>'
            f'      <w:bottom w:val="single" w:sz="12" w:space="1" w:color="{HEX_ORANGE}"/>'
            f'    </w:pBdr>'
            f'    <w:spacing w:before="160" w:after="160"/>'
            f'  </w:pPr>'
            f'</w:p>'
        )
    before_element.addprevious(divider)


def create_header_block(doc, title=None, subtitle=None, doc_type="general"):
    """
    Create a branded header block at the top of the document with:
    - Top colored ribbon (orange + blue double line)
    - Company name "PECH GROUP HOLDINGS LTD" in dark blue
    - Document title in sky blue
    - Optional subtitle in dark orange
    - Bottom colored ribbon

    If title is not provided, it's auto-detected from the document's first H1 heading.
    """
    # Auto-detect title from first heading if not provided
    if title is None:
        for p in doc.paragraphs:
            if p.style and p.style.name == "Heading 1" and p.text.strip():
                title = p.text.strip()
                break
        if title is None:
            title = "PECH Document"

    body = doc.element.body
    first_element = body[0] if len(body) > 0 else None

    elements_to_insert = []

    # ── Top ribbon: thick orange line ──
    ribbon_top = parse_xml(
        f'<w:p {nsdecls("w")}>'
        f'  <w:pPr>'
        f'    <w:pBdr>'
        f'      <w:top w:val="single" w:sz="36" w:space="0" w:color="{HEX_ORANGE}"/>'
        f'      <w:bottom w:val="single" w:sz="12" w:space="1" w:color="{HEX_SKY_BLUE}"/>'
        f'    </w:pBdr>'
        f'    <w:spacing w:after="0"/>'
        f'  </w:pPr>'
        f'</w:p>'
    )
    elements_to_insert.append(ribbon_top)

    # ── Company name ──
    company = parse_xml(
        f'<w:p {nsdecls("w")}>'
        f'  <w:pPr>'
        f'    <w:jc w:val="center"/>'
        f'    <w:spacing w:before="200" w:after="40"/>'
        f'  </w:pPr>'
        f'  <w:r>'
        f'    <w:rPr>'
        f'      <w:b/>'
        f'      <w:color w:val="{HEX_DARK_BLUE}"/>'
        f'      <w:sz w:val="28"/>'
        f'      <w:szCs w:val="28"/>'
        f'    </w:rPr>'
        f'    <w:t>PECH GROUP HOLDINGS LTD</w:t>'
        f'  </w:r>'
        f'</w:p>'
    )
    elements_to_insert.append(company)

    # ── Tagline ──
    tagline = parse_xml(
        f'<w:p {nsdecls("w")}>'
        f'  <w:pPr>'
        f'    <w:jc w:val="center"/>'
        f'    <w:spacing w:before="0" w:after="60"/>'
        f'  </w:pPr>'
        f'  <w:r>'
        f'    <w:rPr>'
        f'      <w:i/>'
        f'      <w:color w:val="{HEX_DARK_ORANGE}"/>'
        f'      <w:sz w:val="18"/>'
        f'      <w:szCs w:val="18"/>'
        f'    </w:rPr>'
        f'    <w:t>Technology &amp; Infrastructure Enablers for Africa</w:t>'
        f'  </w:r>'
        f'</w:p>'
    )
    elements_to_insert.append(tagline)

    # ── Thin separator ──
    thin_sep = parse_xml(
        f'<w:p {nsdecls("w")}>'
        f'  <w:pPr>'
        f'    <w:pBdr>'
        f'      <w:bottom w:val="single" w:sz="6" w:space="1" w:color="{HEX_SKY_BLUE}"/>'
        f'    </w:pBdr>'
        f'    <w:spacing w:before="0" w:after="120"/>'
        f'  </w:pPr>'
        f'</w:p>'
    )
    elements_to_insert.append(thin_sep)

    # ── Bottom ribbon: orange + blue double ──
    ribbon_bottom = parse_xml(
        f'<w:p {nsdecls("w")}>'
        f'  <w:pPr>'
        f'    <w:pBdr>'
        f'      <w:top w:val="single" w:sz="12" w:space="1" w:color="{HEX_SKY_BLUE}"/>'
        f'      <w:bottom w:val="single" w:sz="36" w:space="0" w:color="{HEX_ORANGE}"/>'
        f'    </w:pBdr>'
        f'    <w:spacing w:before="0" w:after="240"/>'
        f'  </w:pPr>'
        f'</w:p>'
    )
    elements_to_insert.append(ribbon_bottom)

    # Insert all elements at the top of the document (in reverse order before first element)
    if first_element is not None:
        for elem in reversed(elements_to_insert):
            first_element.addprevious(elem)
    else:
        for elem in elements_to_insert:
            body.append(elem)


def add_footer_ribbon(doc):
    """Add a branded footer ribbon at the very end of the document."""
    body = doc.element.body

    # ── Footer separator ──
    footer_sep = parse_xml(
        f'<w:p {nsdecls("w")}>'
        f'  <w:pPr>'
        f'    <w:pBdr>'
        f'      <w:top w:val="single" w:sz="36" w:space="1" w:color="{HEX_ORANGE}"/>'
        f'      <w:bottom w:val="single" w:sz="12" w:space="0" w:color="{HEX_SKY_BLUE}"/>'
        f'    </w:pBdr>'
        f'    <w:spacing w:before="300" w:after="0"/>'
        f'  </w:pPr>'
        f'</w:p>'
    )
    body.append(footer_sep)

    # ── Footer text ──
    footer_text = parse_xml(
        f'<w:p {nsdecls("w")}>'
        f'  <w:pPr>'
        f'    <w:jc w:val="center"/>'
        f'    <w:spacing w:before="60" w:after="0"/>'
        f'  </w:pPr>'
        f'  <w:r>'
        f'    <w:rPr>'
        f'      <w:color w:val="{HEX_DARK_BLUE}"/>'
        f'      <w:sz w:val="16"/>'
        f'      <w:szCs w:val="16"/>'
        f'    </w:rPr>'
        f'    <w:t xml:space="preserve">PECH Group Holdings Ltd  |  Lagos, Nigeria  |  pechgroupholdings.tech</w:t>'
        f'  </w:r>'
        f'</w:p>'
    )
    body.append(footer_text)


def style_headings(doc):
    """Apply brand colors to all headings in the document."""
    for paragraph in doc.paragraphs:
        style_name = paragraph.style.name if paragraph.style else ""

        if style_name == "Heading 1":
            # H1: Dark Blue text + orange bottom border
            set_all_runs_color(paragraph, DARK_BLUE)
            # Also set paragraph-level color for runs without explicit formatting
            _set_paragraph_font_color(paragraph, HEX_DARK_BLUE)
            set_paragraph_border_bottom(paragraph, HEX_ORANGE, size_eighths=18, space=2)
            # Make bold
            for run in paragraph.runs:
                run.font.bold = True
                run.font.size = Pt(22)

        elif style_name == "Heading 2":
            # H2: Dark Blue text + thin sky blue bottom border
            set_all_runs_color(paragraph, DARK_BLUE)
            _set_paragraph_font_color(paragraph, HEX_DARK_BLUE)
            set_paragraph_border_bottom(paragraph, HEX_SKY_BLUE, size_eighths=6, space=2)
            for run in paragraph.runs:
                run.font.bold = True
                run.font.size = Pt(16)

        elif style_name == "Heading 3":
            # H3: Dark Orange
            set_all_runs_color(paragraph, DARK_ORANGE)
            _set_paragraph_font_color(paragraph, HEX_DARK_ORANGE)
            for run in paragraph.runs:
                run.font.bold = True
                run.font.size = Pt(13)

        elif style_name == "Heading 4":
            # H4: Sky Blue
            set_all_runs_color(paragraph, SKY_BLUE)
            _set_paragraph_font_color(paragraph, HEX_SKY_BLUE)
            for run in paragraph.runs:
                run.font.bold = True
                run.font.size = Pt(11)


def _set_paragraph_font_color(paragraph, hex_color):
    """Set default font color at paragraph level (for text without explicit run formatting)."""
    pPr = paragraph._element.get_or_add_pPr()
    rPr = pPr.find(qn('w:rPr'))
    if rPr is None:
        rPr = parse_xml(f'<w:rPr {nsdecls("w")}></w:rPr>')
        pPr.append(rPr)
    color_elem = rPr.find(qn('w:color'))
    if color_elem is None:
        color_elem = parse_xml(f'<w:color {nsdecls("w")} w:val="{hex_color}"/>')
        rPr.append(color_elem)
    else:
        color_elem.set(qn('w:val'), hex_color)


def style_tables(doc):
    """Apply brand colors to all tables: blue header row, alternating row colors, borders."""
    for table in doc.tables:
        # Style the table borders
        tbl = table._tbl
        tblPr = tbl.find(qn('w:tblPr'))
        if tblPr is None:
            tblPr = parse_xml(f'<w:tblPr {nsdecls("w")}></w:tblPr>')
            tbl.insert(0, tblPr)

        # Set table borders
        borders_xml = (
            f'<w:tblBorders {nsdecls("w")}>'
            f'  <w:top w:val="single" w:sz="4" w:space="0" w:color="{HEX_BORDER_LIGHT}"/>'
            f'  <w:left w:val="single" w:sz="4" w:space="0" w:color="{HEX_BORDER_LIGHT}"/>'
            f'  <w:bottom w:val="single" w:sz="4" w:space="0" w:color="{HEX_BORDER_LIGHT}"/>'
            f'  <w:right w:val="single" w:sz="4" w:space="0" w:color="{HEX_BORDER_LIGHT}"/>'
            f'  <w:insideH w:val="single" w:sz="4" w:space="0" w:color="{HEX_BORDER_LIGHT}"/>'
            f'  <w:insideV w:val="single" w:sz="4" w:space="0" w:color="{HEX_BORDER_LIGHT}"/>'
            f'</w:tblBorders>'
        )
        existing_borders = tblPr.find(qn('w:tblBorders'))
        if existing_borders is not None:
            tblPr.remove(existing_borders)
        tblPr.append(parse_xml(borders_xml))

        # Style rows
        for row_idx, row in enumerate(table.rows):
            if row_idx == 0:
                # Header row: dark blue background, white text
                for cell in row.cells:
                    # Remove any existing shading
                    tcPr = cell._tc.get_or_add_tcPr()
                    existing_shd = tcPr.find(qn('w:shd'))
                    if existing_shd is not None:
                        tcPr.remove(existing_shd)
                    set_cell_shading(cell, HEX_DARK_BLUE)
                    set_cell_text_color(cell, WHITE)
                    # Make header text bold
                    for p in cell.paragraphs:
                        for run in p.runs:
                            run.font.bold = True
                            run.font.size = Pt(10)
            else:
                # Alternating rows
                bg_color = HEX_LIGHT_BLUE if row_idx % 2 == 0 else HEX_WHITE
                for cell in row.cells:
                    tcPr = cell._tc.get_or_add_tcPr()
                    existing_shd = tcPr.find(qn('w:shd'))
                    if existing_shd is not None:
                        tcPr.remove(existing_shd)
                    set_cell_shading(cell, bg_color)
                    set_cell_text_color(cell, BODY_TEXT)
                    for p in cell.paragraphs:
                        for run in p.runs:
                            run.font.size = Pt(9.5)


def insert_dividers_before_h2(doc):
    """
    Insert branded colored dividers (horizontal rules) before each H2 heading.
    This replaces the markdown --- dividers that pandoc strips out.
    """
    body = doc.element.body
    # Collect H2 elements first (to avoid modifying during iteration)
    h2_elements = []
    for p in doc.paragraphs:
        if p.style and p.style.name == "Heading 2":
            h2_elements.append(p._element)

    for elem in h2_elements:
        insert_branded_divider(doc, elem, style="double")


def style_blockquotes(doc):
    """Style blockquotes (Block Text style) with orange left border and light background."""
    for paragraph in doc.paragraphs:
        if paragraph.style and paragraph.style.name == "Block Text":
            pPr = paragraph._element.get_or_add_pPr()
            # Add orange left border
            pBdr = pPr.find(qn('w:pBdr'))
            if pBdr is None:
                pBdr = parse_xml(f'<w:pBdr {nsdecls("w")}></w:pBdr>')
                pPr.append(pBdr)
            left = parse_xml(
                f'<w:left {nsdecls("w")} w:val="single" w:sz="24" '
                f'w:space="6" w:color="{HEX_ORANGE}"/>'
            )
            existing = pBdr.find(qn('w:left'))
            if existing is not None:
                pBdr.remove(existing)
            pBdr.append(left)

            # Light yellow background
            shd = parse_xml(
                f'<w:shd {nsdecls("w")} w:fill="FFF8E1" w:val="clear"/>'
            )
            existing_shd = pPr.find(qn('w:shd'))
            if existing_shd is not None:
                pPr.remove(existing_shd)
            pPr.append(shd)


def style_code_blocks(doc):
    """Style code blocks (Source Code style) with dark navy background and sky blue text."""
    for paragraph in doc.paragraphs:
        if paragraph.style and paragraph.style.name == "Source Code":
            pPr = paragraph._element.get_or_add_pPr()
            # Dark navy background
            shd = parse_xml(
                f'<w:shd {nsdecls("w")} w:fill="{HEX_DARK_NAVY}" w:val="clear"/>'
            )
            existing_shd = pPr.find(qn('w:shd'))
            if existing_shd is not None:
                pPr.remove(existing_shd)
            pPr.append(shd)

            # Sky blue text
            for run in paragraph.runs:
                run.font.color.rgb = SKY_BLUE


def clean_markdown_artifacts(doc):
    """
    Clean up any remaining markdown syntax artifacts in the DOCX text.

    Fixes:
    - **bold** markers → actual bold formatting
    - [text](#anchor) links → plain text
    - Removes empty paragraphs with only whitespace or unicode lines
    - Removes duplicate "PECH GROUP HOLDINGS LTD" text from body
    """
    company_name_seen = False

    for paragraph in doc.paragraphs:
        text = paragraph.text

        # Remove paragraphs that are just unicode line characters (━━━)
        if text.strip() and all(c in '━─═─▬▰▱░▒▓' for c in text.strip()):
            p_element = paragraph._element
            p_element.getparent().remove(p_element)
            continue

        # Track and remove duplicate company name mentions from body text
        # (the branded header block adds its own, so body ones are duplicates)
        if text.strip() == 'PECH GROUP HOLDINGS LTD':
            if company_name_seen:
                p_element = paragraph._element
                p_element.getparent().remove(p_element)
                continue
            company_name_seen = True

        # Fix **bold** markers in runs — make text actually bold
        for run in paragraph.runs:
            if '**' in run.text:
                # Split on ** markers and rebuild
                parts = run.text.split('**')
                if len(parts) >= 3:
                    # Rebuild: even-indexed parts are normal, odd-indexed are bold
                    new_text = ''.join(parts)
                    run.text = new_text
                    # If the whole run was **text**, make it bold
                    if len(parts) == 3 and parts[0] == '' and parts[2] == '':
                        run.font.bold = True
                    elif len(parts) == 3 and parts[0] == '':
                        run.font.bold = True
                    else:
                        run.font.bold = True

        # Fix [text](#anchor) markdown link patterns in runs
        for run in paragraph.runs:
            if '](#' in run.text or '][' in run.text:
                # Replace [text](#anchor) with just text
                cleaned = re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', run.text)
                # Replace [text][ref] with just text
                cleaned = re.sub(r'\[([^\]]+)\]\[[^\]]*\]', r'\1', cleaned)
                run.text = cleaned


def clean_table_of_contents(doc):
    """
    Fix Table of Contents entries that show raw markdown links.
    Convert [1. Title](#anchor) numbered items to clean text.
    """
    for paragraph in doc.paragraphs:
        style_name = paragraph.style.name if paragraph.style else ""
        if style_name.startswith("List"):
            for run in paragraph.runs:
                if '](#' in run.text:
                    run.text = re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', run.text)


def brand_docx(docx_path):
    """
    Apply full PECH branding to a DOCX file:
    0. Clean markdown artifacts (**bold**, [links], unicode lines, duplicates)
    1. Branded header block (company name + ribbons) — single instance only
    2. Colored headings (H1=dark blue+orange underline, H2=dark blue+blue underline, H3=orange, H4=sky blue)
    3. Colored dividers before each H2 section
    4. Branded tables (blue header, alternating rows)
    5. Styled blockquotes (orange left border)
    6. Styled code blocks (dark navy background)
    7. Footer ribbon — single instance only
    """
    docx_path = Path(docx_path)
    if not docx_path.exists():
        print(f"  SKIP: {docx_path} not found")
        return False

    print(f"  Branding: {docx_path.name}")

    try:
        doc = Document(str(docx_path))

        # Clean up markdown artifacts FIRST (before adding branding)
        clean_markdown_artifacts(doc)
        clean_table_of_contents(doc)

        # Apply all branding transformations
        create_header_block(doc)
        style_headings(doc)
        insert_dividers_before_h2(doc)
        style_tables(doc)
        style_blockquotes(doc)
        style_code_blocks(doc)
        add_footer_ribbon(doc)

        # Save
        doc.save(str(docx_path))
        print(f"  + Branded: {docx_path.name}")
        return True

    except Exception as e:
        print(f"  x FAILED: {docx_path.name} — {e}")
        return False


# ── Collect all DOCX files ────────────────────────────────────────────────────

def find_all_docx():
    """Find all DOCX files in the project that should be branded."""
    docx_files = []

    # Root-level proposal docs
    for f in PROJECT_ROOT.glob("*.docx"):
        docx_files.append(f)

    # AI Strategy docs
    ai_dir = PROJECT_ROOT / "ai_strategy"
    if ai_dir.exists():
        for f in ai_dir.glob("*.docx"):
            docx_files.append(f)

    # Brand templates
    brand_dir = PROJECT_ROOT / "brand_templates"
    if brand_dir.exists():
        for f in brand_dir.glob("*.docx"):
            docx_files.append(f)

    # Business documents
    biz_dir = PROJECT_ROOT / "business_documents"
    if biz_dir.exists():
        for f in biz_dir.glob("*.docx"):
            docx_files.append(f)

    # Contracts
    contracts_dir = PROJECT_ROOT / "contracts"
    if contracts_dir.exists():
        for f in contracts_dir.glob("*.docx"):
            docx_files.append(f)

    return sorted(docx_files)


def main():
    print("=" * 65)
    print("  PECH DOCX Branding Post-Processor")
    print("  Applying brand colors, headers, dividers, and table styling")
    print("=" * 65)
    print()

    if len(sys.argv) > 1:
        # Process specific file(s)
        files = [Path(f) for f in sys.argv[1:]]
    else:
        # Process all DOCX files
        files = find_all_docx()

    if not files:
        print("No DOCX files found to process.")
        return

    print(f"Found {len(files)} DOCX files to brand.\n")

    success = 0
    failed = 0
    for f in files:
        if brand_docx(f):
            success += 1
        else:
            failed += 1

    print()
    print("=" * 65)
    print(f"  Done! {success} branded, {failed} failed/skipped")
    print("=" * 65)


if __name__ == "__main__":
    main()
